### ISSUE TITLE
Hard to compose iterators together

### ISSUE THREAD

**Issue by sammy-hughes** [serge-hulne/go_iter#1]
I have some performance concerns regarding the use of channels as the only way to propagate, but there's not a nice way for you to address that without, like, rewriting the whole thing. So I'll complain about something that's straightforward enough:

currently, your worker interface takes two channels and returns nil. Instead, a worker should be expected to take a context and a  receive-only channel, returning a new context and a new receive-only channel. This change would ensure that the responsibility for each channel is clear, error propagation on a pipeline is controlled at each step by the propagator, and the implementor is far less likely to leave a thread hanging in the background, still running.

Unfortunately, I'd still have the doesn't-know-how-to-share-memory issue, so I'd still be using native loops and/or chains of reader/writer interfaces for same-thread iteration.

**Comment by serge-hulne** [comment]
The iterators are composed as follows:

```
        // Callbacks:
	filter_even := func(c1, c2 chan int) chan int {
		for item := range c1 {
			if item%2 == 0 {
				c2 <- item
			}
		}
		return c2
	}

	map_to_square := func(c1, c2 chan int) chan int {
		for item := range c1 {
			c2 <- item * item
		}
		return c2
	}

	// Data
	nums := []int{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

	// Data -> iterator:
	fmt.Println("- - -")
	generated := Iterable_from_array(nums)

	// Chaining iterators:
	even := Filter(generated, filter_even)
	even_and_squared := Map(even, map_to_square)

	// Displaying results:
	for item := range even_and_squared {
		fmt.Printf("Gen: %#v\n", item)
	}
```

Regarding the use of context, I will look into it.
