### ISSUE TITLE
Integrate with `samber/lo`

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [serge-hulne/go_iter#2]
I've stumbled upon your repo from [this post](https://serge-hulne.medium.com/iterators-map-filter-reduce-and-list-processing-in-go-golang-implementing-python-functional-2d24d780051f). It's great to have this lazy iterators for efficient chaining of operations in go!

Since https://github.com/samber/lo is the biggest functional programming library for go, have you considered integrating this into it?

**Comment by serge-hulne** [comment]
Thank you, I'll look into it.

**Comment by serge-hulne** [comment]
Thanks for your contributions (commits).
I'll integrate them into go_iter.
