### ISSUE TITLE
If the parent function returns early, you end up with blocked orphaned go-routines

### ISSUE THREAD

**Issue by demossjoshua** [serge-hulne/go_iter#4]
## If the parent function returns early, you end up with blocked orphaned go-routines

In each case, you use a go-routine to populate the channel you are ranging over, and as you said, that blocks until the next element is read using the range function. Isn't this problematic if you do error handling in the for loop? Even though it won't block the main thread, wouldn't the go-routine block and stay around forever as long as the main thread runs? If this is a server, then as long as the server is alive? If it serves many requests, you might just keep adding more and more go-routines!

Example:

```
for item := range Range(10) {
	if item == 2 {
		return
	}
}
```

The previous example would return without reading the rest of the ints in the channel and thus leave the orphaned go-routine around.

## Full example file that demonstrates the orphaned go-routines getting created:
```
package main

import (
	"fmt"
	"runtime"

	"github.com/lucemhealth/go-common/lucemtelemetry"
)

func main() {
	lucemtelemetry.ConfigureZerologLogger()

	for i := 0; i < 10; i++ {
		fmt.Printf("request number: %d\n", i)
		fmt.Printf("starting number of routines: %d\n", runtime.NumGoroutine())
		doForLoop()
		fmt.Printf("ending number of routines: %d\n", runtime.NumGoroutine())
		fmt.Println()
	}
}

func doForLoop() {
	for item := range Range(10) {
		if item == 2 {
			return
		}
	}
}

func Range(nmax int) chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for index := 0; index < nmax; index++ {
			out <- index
		}
	}()
	return out
}
```

**Comment by serge-hulne** [comment]
What about adding a CleanIter() function:
```
package main

import (
	"fmt"
	"runtime"
	"sync"
)

var wg sync.WaitGroup

func CleanIteraor[T any](r chan T) {
	for _ = range r {
	}
}

func main() {
	for i := 0; i < 10; i++ {
		fmt.Printf("request number: %d\n", i)
		fmt.Printf("starting number of routines: %d\n", runtime.NumGoroutine())
		wg.Add(1)
		doForLoop()
		fmt.Printf("ending number of routines: %d\n", runtime.NumGoroutine())
		fmt.Println()
	}
	wg.Wait()

	fmt.Printf("Final number of routines: %d\n", runtime.NumGoroutine())

}

func doForLoop() {
	defer wg.Done()
	r := Range(10)
	defer CleanIteraor(r)
	for item := range r {
		if item == 2 {
			return
		}
		//fmt.Printf("value : %d\n", item)
	}

}

func Range(nmax int) chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for index := 0; index < nmax; index++ {
			out <- index
		}
	}()
	return out
}

```

**Comment by serge-hulne** [comment]
> ## If the parent function returns early, you end up with blocked orphaned go-routines
> In each case, you use a go-routine to populate the channel you are ranging over, and as you said, that blocks until the next element is read using the range function. Isn't this problematic if you do error handling in the for loop? Even though it won't block the main thread, wouldn't the go-routine block and stay around forever as long as the main thread runs? If this is a server, then as long as the server is alive? If it serves many requests, you might just keep adding more and more go-routines!
> 
> Example:
> 
> ```
> for item := range Range(10) {
> 	if item == 2 {
> 		return
> 	}
> }
> ```
> 
> The previous example would return without reading the rest of the ints in the channel and thus leave the orphaned go-routine around.
> 
> ## Full example file that demonstrates the orphaned go-routines getting created:
> ```
> package main
> 
> import (
> 	"fmt"
> 	"runtime"
> 
> 	"github.com/lucemhealth/go-common/lucemtelemetry"
> )
> 
> func main() {
> 	lucemtelemetry.ConfigureZerologLogger()
> 
> 	for i := 0; i < 10; i++ {
> 		fmt.Printf("request number: %d\n", i)
> 		fmt.Printf("starting number of routines: %d\n", runtime.NumGoroutine())
> 		doForLoop()
> 		fmt.Printf("ending number of routines: %d\n", runtime.NumGoroutine())
> 		fmt.Println()
> 	}
> }
> 
> func doForLoop() {
> 	for item := range Range(10) {
> 		if item == 2 {
> 			return
> 		}
> 	}
> }
> 
> func Range(nmax int) chan int {
> 	out := make(chan int)
> 	go func() {
> 		defer close(out)
> 		for index := 0; index < nmax; index++ {
> 			out <- index
> 		}
> 	}()
> 	return out
> }
> ```

What about:

```
package main

import (
	"fmt"
	"runtime"
	"sync"
)

var wg sync.WaitGroup

func CleanIteraor[T any](r chan T) {
	for _ = range r {
	}
}

func main() {
	for i := 0; i < 10; i++ {
		fmt.Printf("request number: %d\n", i)
		fmt.Printf("starting number of routines: %d\n", runtime.NumGoroutine())
		wg.Add(1)
		doForLoop()
		fmt.Printf("ending number of routines: %d\n", runtime.NumGoroutine())
		fmt.Println()
	}
	wg.Wait()

	fmt.Printf("Final number of routines: %d\n", runtime.NumGoroutine())

}

func doForLoop() {
	defer wg.Done()
	r := Range(10)
	defer CleanIteraor(r)
	for item := range r {
		if item == 2 {
			return
		}
		//fmt.Printf("value : %d\n", item)
	}

}

func Range(nmax int) chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for index := 0; index < nmax; index++ {
			out <- index
		}
	}()
	return out
}

```
